version: '3.8'

services:
  blog-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
